---
kind: pipeline
name: release
type: kubernetes

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

anchors:
  - &go-image
    image: golang:1.16

trigger:
  event:
    - tag

steps:
  - name: build-linux
    << : *go-image
    commands:
      - go mod tidy
      - go build -o drone-cache -ldflags="-X 'github.com/Hotmart-Org/drone-cache/core.Version=$DRONE_TAG'"
    environment:
      GOOS: linux
      GARCH: amd64
      CGO_ENABLED: 0
    depends_on:
      - clone

  - name: build-zip
    image: public.ecr.aws/hotmart/pipeline-utils:latest
    commands:
      - apk add zip
      - zip -j linux.zip drone-cache
    depends_on:
      - build-linux

  - name: create-release
    image: public.ecr.aws/hotmart/pipeline-utils:latest
    commands:
      - export GIT_MESSAGE=$(git log -n 1 --format=%B)
      - gh release upload "${DRONE_TAG}" linux.zip
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    depends_on:
      - build-zip
    
---
kind: secret
name: github_token
get:
  path: kv/data/drone/github
  name: token
