---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 50

steps:
  - name: build-linux
    image: golang:1.16
    commands:
      - go mod tidy
      - go build -o drone-cache -ldflags="-X 'github.com/Hotmart-Org/drone-cache/core.Version=$DRONE_TAG'"
    environment:
      GOOS: linux
      GARCH: amd64
      CGO_ENABLED: 0
    depends_on:
      - clone

  - name: build-zip
    image: public.ecr.aws/hotmart/pipeline-utils:latest
    commands:
      - apk add zip
      - zip -j linux.zip hotpoint
    depends_on:
      - build-linux

  - name: create-release
    image: public.ecr.aws/hotmart/pipeline-utils:latest
    commands:
      - export GIT_MESSAGE=$(git log -n 1 --format=%B)
      - gh release upload "${DRONE_TAG}" linux.zip
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    depends_on:
      - build-zip

trigger:
  event:
    - tag
